### ISSUE TITLE
failed to lunch sysmodule "2005-0012"

### ISSUE THREAD

**Issue by salem193** [HookedBehemoth/sys-tune#20] opened 2020-11-21 10:45 UTC
hi @HookedBehemoth 

i was using“sys-tune” since one week but yesterday tried to open it as usual But this error message appeared “Failed to launch sysmodule .2005-0012“

FW: SXOS 3.0.5 / FW: 10.2.0

sys-tune 1.2.1
Tesla menu 1.1.3
nx-ovlloader 1.0.6

**Comment by HookedBehemoth** [comment] 2020-11-24 19:20
Does this also happen on Atmosphère?

**Comment by salem193** [comment] 2020-11-25 07:31
i am SXOS user so i don't know if that happen also with Atmosphère

**Comment by HookedBehemoth** [comment] 2020-12-06 14:39
closing because I can't reproduce

**Closed by HookedBehemoth** 2020-12-06 14:39 UTC
